const defaults=[{id:1,cat:'startup',icon:'▦',title:'تأسيس الشركات',desc:'من اختيار الكيان حتى إصدار السجل وتجهيز المنشأة للتشغيل.',color:'#e5f5ff'},{id:2,cat:'government',icon:'⌁',title:'الخدمات الحكومية',desc:'تنفيذ ومتابعة معاملات المنشأة عبر الجهات والمنصات ذات العلاقة.',color:'#e8f9f5'},{id:3,cat:'government',icon:'٪',title:'الزكاة والضريبة',desc:'خدمات التسجيل والإقرارات والمتابعة المحاسبية للمنشآت.',color:'#fff5dd'},{id:4,cat:'government',icon:'♙',title:'الموارد البشرية',desc:'خدمات قوى ومدد والتأمينات وتنظيم دورة حياة الموظف.',color:'#f0edff'},{id:5,cat:'consulting',icon:'◎',title:'دراسات الجدوى',desc:'دراسة السوق والجوانب الفنية والمالية قبل قرار الاستثمار.',color:'#e5f8f8'},{id:6,cat:'consulting',icon:'⌘',title:'الحوكمة والامتثال',desc:'أطر واضحة للصلاحيات والسياسات والمخاطر واستدامة القرار.',color:'#eaf0ff'},{id:7,cat:'growth',icon:'↗',title:'التخطيط ومؤشرات الأداء',desc:'تحويل الرؤية إلى أهداف ومبادرات ومؤشرات قابلة للقياس.',color:'#e7f8f1'},{id:8,cat:'growth',icon:'✓',title:'الجودة وشهادات ISO',desc:'تحليل الفجوات وبناء الأنظمة والتأهيل لمتطلبات الجودة.',color:'#eaf7ff'},{id:9,cat:'government',icon:'⌂',title:'التراخيص البلدية والسلامة',desc:'إصدار وتجديد التراخيص ومتابعة متطلبات السلامة.',color:'#fff2e8'},{id:10,cat:'growth',icon:'◈',title:'التحول الرقمي',desc:'أتمتة الإجراءات وربط البيانات وبناء لوحات قيادة للأعمال.',color:'#e9f5ff'},{id:11,cat:'startup',icon:'◇',title:'خدمات المستثمرين',desc:'مسار تأسيس منظم للمستثمر السعودي والخليجي والأجنبي.',color:'#eef9e9'},{id:12,cat:'government',icon:'®',title:'الملكية الفكرية',desc:'تسجيل العلامات التجارية ومتابعة الطلبات وحماية الأصول.',color:'#f7edff'}];
let services=JSON.parse(localStorage.getItem('madar_services')||'null')||defaults;
const titles={overview:'نظرة عامة',content:'الهوية والمحتوى',media:'الصور والحركة',services:'إدارة الخدمات',orders:'إدارة الطلبات',analytics:'التقارير والتحليلات'};
document.querySelectorAll('aside nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('aside nav button,.admin-page').forEach(x=>x.classList.remove('active'));
b.classList.add('active');
document.getElementById(b.dataset.page).classList.add('active');
document.getElementById('pageTitle').textContent=titles[b.dataset.page]});
const settings=JSON.parse(localStorage.getItem('madar_settings')||'{}');
brandInput.value=settings.brand||'مَدار';
colorInput.value=settings.primary||'#1477c9';
phoneInput.value=settings.phone||'+966 50 000 0000';
heroTitleInput.value=settings.heroTitle||'كل ما تحتاجه منشأتك | في مسار واحد واضح.';
heroSubtitleInput.value=settings.heroSubtitle||'نؤسس أعمالك، ننفّذ معاملاتك، ونطوّر منظومتك الإدارية بمتابعة شفافة من أول طلب حتى الإنجاز.';
motionInput.value=settings.motion||'on';
motionLevelInput.value=settings.motionLevel||'soft';
settingsForm.onsubmit=e=>{e.preventDefault();
Object.assign(settings,{brand:brandInput.value,primary:colorInput.value,phone:phoneInput.value});
localStorage.setItem('madar_settings',JSON.stringify(settings));
toast('تم حفظ إعدادات الهوية')};
mediaForm.onsubmit=e=>{e.preventDefault();
Object.assign(settings,{heroTitle:heroTitleInput.value,heroSubtitle:heroSubtitleInput.value,motion:motionInput.value,motionLevel:motionLevelInput.value});
localStorage.setItem('madar_settings',JSON.stringify(settings));
toast('تم حفظ إعدادات الصور والحركة')};
function render(){serviceCount.textContent=services.length;
serviceAdminList.innerHTML=services.map(s=>`<article class="service-item"><i>${s.icon}</i><div><b>${s.title}</b><small>${s.cat}</small></div><button data-delete="${s.id}" title="حذف">×</button></article>`).join('')}render();
serviceAdminList.onclick=e=>{const b=e.target.closest('[data-delete]');
if(!b)return;
services=services.filter(s=>s.id!==+b.dataset.delete);
localStorage.setItem('madar_services',JSON.stringify(services));
render();
toast('تم حذف الخدمة من هذه النسخة')};
addService.onclick=()=>{const title=prompt('اسم الخدمة الجديدة');
if(!title)return;
const desc=prompt('وصف مختصر للخدمة')||'خدمة أعمال متخصصة قابلة للتخصيص حسب احتياج المنشأة.';
services.push({id:Date.now(),cat:'consulting',icon:'✦',title,desc,color:'#e8f5fd'});
localStorage.setItem('madar_services',JSON.stringify(services));
render();
toast('تمت إضافة الخدمة')};
function toast(m){adminToast.textContent=m;
adminToast.classList.add('show');
setTimeout(()=>adminToast.classList.remove('show'),2300)}
