const $=selector=>document.querySelector(selector);
const clean=(value,max=300)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max);
const esc=value=>clean(value,600).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let content=null;
const sectionNames={visualStory:'الصور والأنشطة الرئيسية',marquee:'شريط القطاعات المتحرك',saudiValue:'القيمة للسوق السعودي',method:'منهجية العمل والإنفوجرافيك',services:'مستكشف الخدمات',journey:'رحلة تنفيذ الخدمة',transformation:'المقارنة قبل وبعد',solutions:'حلول مراحل المنشأة',packages:'الباقات',track:'تتبع الطلبات',knowledge:'مركز المعرفة',deliverables:'المخرجات والتسليمات',faq:'الأسئلة الشائعة',cta:'الدعوة الختامية للتواصل'};
const titles={overview:'نظرة عامة',content:'الهوية والمحتوى',media:'الصور والأنشطة',articles:'مركز المعرفة',services:'إدارة الخدمات',sections:'عرض الأقسام'};

async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{'content-type':'application/json','x-requested-with':'MadarAdmin',...(options.headers||{})}});const data=await response.json().catch(()=>({error:'استجابة غير صالحة'}));if(!response.ok)throw new Error(data.error||'تعذر إكمال العملية');return data}
function toast(message,type='ok'){$('#adminToast').textContent=message;$('#adminToast').className=`toast show ${type}`;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#adminToast').className='toast',2600)}
function setBusy(busy,label='جارٍ الحفظ…'){$('#saveState').textContent=busy?label:'تم الحفظ';document.body.classList.toggle('saving',busy)}

document.querySelectorAll('aside nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('aside nav button,.admin-page').forEach(x=>x.classList.remove('active'));button.classList.add('active');$('#'+button.dataset.page).classList.add('active');$('#pageTitle').textContent=titles[button.dataset.page]}));

async function start(){try{const session=await api('/api/admin/session',{method:'GET'});if(session.authenticated){$('#loginGate').classList.add('hidden');await loadContent()}else{$('#loginGate').classList.remove('hidden');if(!session.configured)$('#loginError').textContent='يلزم ضبط ADMIN_PASSWORD في إعدادات الخادم أولًا.'}}catch{$('#loginError').textContent='تعذر الاتصال بالخادم، حاول تحديث الصفحة.'}}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();$('#loginError').textContent='';const button=event.submitter;button.disabled=true;button.textContent='جارٍ التحقق…';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#passwordInput').value})});$('#passwordInput').value='';$('#loginGate').classList.add('hidden');await loadContent();toast('تم تسجيل الدخول بنجاح')}catch(error){$('#loginError').textContent=error.message}finally{button.disabled=false;button.textContent='دخول آمن'}});
$('#logoutBtn').addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST'})}finally{location.reload()}});

async function loadContent(){content=await api('/api/content',{method:'GET'});fillSettings();renderAll()}
function fillSettings(){const s=content.settings;$('#brandInput').value=s.brand;$('#colorInput').value=s.primary;$('#phoneInput').value=s.phone;$('#emailInput').value=s.email;$('#cityInput').value=s.city;$('#heroTitleInput').value=s.heroTitle;$('#heroSubtitleInput').value=s.heroSubtitle;$('#motionInput').value=s.motion;$('#motionLevelInput').value=s.motionLevel}
function renderAll(){renderActivities();renderArticles();renderServices();renderVisibility();updateCounts()}
function updateCounts(){$('#serviceCount').textContent=content.services.length;$('#activityCount').textContent=content.activities.length;$('#articleCount').textContent=content.articles.length;$('#sectionCount').textContent=Object.values(content.visibility).filter(Boolean).length}
async function save(message){setBusy(true);try{content=await api('/api/admin/content',{method:'PUT',body:JSON.stringify(content)});renderAll();toast(message)}catch(error){toast(error.message,'error');if(/تسجيل الدخول/.test(error.message))location.reload()}finally{setBusy(false)}}

$('#settingsForm').addEventListener('submit',event=>{event.preventDefault();content.settings={brand:clean($('#brandInput').value,40),primary:$('#colorInput').value,phone:clean($('#phoneInput').value,24),email:clean($('#emailInput').value,100),city:clean($('#cityInput').value,100),heroTitle:clean($('#heroTitleInput').value,140),heroSubtitle:clean($('#heroSubtitleInput').value,300),motion:$('#motionInput').value,motionLevel:$('#motionLevelInput').value};save('تم نشر إعدادات الهوية')});

function imageEditor(item,index,type){return `<article class="editor-card" data-index="${index}" data-type="${type}"><div class="editor-image"><img src="${esc(item.image)}" alt=""><label class="upload-btn">رفع صورة<input type="file" accept="image/jpeg,image/png,image/webp" data-upload></label><small>JPG أو PNG أو WebP — حتى 2MB</small></div><div class="editor-fields"><label>التصنيف<input data-field="tag" value="${esc(item.tag)}" maxlength="40"></label><label class="wide">العنوان<input data-field="title" value="${esc(item.title)}" maxlength="120"></label><label class="wide">الوصف<textarea data-field="desc" maxlength="260">${esc(item.desc)}</textarea></label><label class="wide">وصف الصورة لمحركات البحث<input data-field="alt" value="${esc(item.alt)}" maxlength="160"></label>${type==='article'?`<label class="wide">رابط المقال<input data-field="link" value="${esc(item.link||'#')}" maxlength="500" dir="ltr"></label>`:''}</div><button class="delete-editor" data-remove title="حذف">×</button></article>`}
function renderActivities(){$('#activityEditor').innerHTML=content.activities.map((x,i)=>imageEditor(x,i,'activity')).join('')||'<div class="empty">لا توجد أنشطة. أضف أول نشاط للبدء.</div>'}
function renderArticles(){$('#articleEditor').innerHTML=content.articles.map((x,i)=>imageEditor(x,i,'article')).join('')||'<div class="empty">لا توجد مقالات منشورة.</div>'}
function collectEditors(type){const key=type==='activity'?'activities':'articles';document.querySelectorAll(`[data-type="${type}"]`).forEach(card=>{const item=content[key][+card.dataset.index];card.querySelectorAll('[data-field]').forEach(input=>item[input.dataset.field]=clean(input.value,input.dataset.field==='desc'?260:input.dataset.field==='link'?500:160))})}
function bindEditor(container,type){container.addEventListener('change',async event=>{const input=event.target.closest('[data-upload]');if(!input)return;const file=input.files[0];if(!file)return;if(file.size>2_000_000)return toast('الصورة أكبر من 2MB','error');const card=input.closest('.editor-card'),button=card.querySelector('.upload-btn');button.classList.add('loading');button.childNodes[0].textContent='جارٍ الرفع…';try{const data=await fileToData(file),result=await api('/api/admin/upload',{method:'POST',body:JSON.stringify({data,name:file.name})});const key=type==='activity'?'activities':'articles';content[key][+card.dataset.index].image=result.url;card.querySelector('img').src=result.url;toast('تم رفع الصورة، اضغط حفظ للنشر')}catch(error){toast(error.message,'error')}finally{button.classList.remove('loading');button.childNodes[0].textContent='رفع صورة'}});container.addEventListener('click',event=>{const remove=event.target.closest('[data-remove]');if(!remove)return;collectEditors(type);const card=remove.closest('.editor-card'),key=type==='activity'?'activities':'articles';content[key].splice(+card.dataset.index,1);type==='activity'?renderActivities():renderArticles();updateCounts()})}
bindEditor($('#activityEditor'),'activity');bindEditor($('#articleEditor'),'article');
function fileToData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
$('#addActivity').addEventListener('click',()=>{collectEditors('activity');if(content.activities.length>=6)return toast('الحد الأقصى 6 أنشطة','error');content.activities.push({id:Date.now(),tag:'نشاط جديد',title:'عنوان النشاط',desc:'وصف مختصر للنشاط.',image:'assets/images/saudi-business-establishment.svg',alt:'صورة نشاط أعمال'});renderActivities();updateCounts()});
$('#addArticle').addEventListener('click',()=>{collectEditors('article');if(content.articles.length>=9)return toast('الحد الأقصى 9 مقالات','error');content.articles.push({id:Date.now(),tag:'مقال',title:'عنوان المقال الجديد',desc:'نبذة مختصرة عن محتوى المقال.',image:'assets/images/company-formation.svg',alt:'صورة المقال',link:'#'});renderArticles();updateCounts()});
$('#saveActivities').addEventListener('click',()=>{collectEditors('activity');save('تم نشر الصور والأنشطة')});
$('#saveArticles').addEventListener('click',()=>{collectEditors('article');save('تم نشر مركز المعرفة')});

function renderServices(){$('#serviceAdminList').innerHTML=content.services.map((s,i)=>`<article class="service-item" data-service-index="${i}"><i style="background:${esc(s.color)}">${esc(s.icon)}</i><div><input data-sfield="title" value="${esc(s.title)}" maxlength="80"><textarea data-sfield="desc" maxlength="220">${esc(s.desc)}</textarea><span><select data-sfield="cat"><option value="startup" ${s.cat==='startup'?'selected':''}>التأسيس</option><option value="government" ${s.cat==='government'?'selected':''}>حكومية</option><option value="consulting" ${s.cat==='consulting'?'selected':''}>استشارات</option><option value="growth" ${s.cat==='growth'?'selected':''}>النمو والجودة</option></select><input class="icon-input" data-sfield="icon" value="${esc(s.icon)}" maxlength="3" title="الرمز"><input type="color" data-sfield="color" value="${esc(s.color)}" title="لون البطاقة"></span></div><button data-delete-service title="حذف">×</button></article>`).join('')||'<div class="empty">لا توجد خدمات حاليًا.</div>'}
$('#serviceAdminList').addEventListener('click',event=>{const button=event.target.closest('[data-delete-service]');if(!button)return;collectServices();content.services.splice(+button.closest('[data-service-index]').dataset.serviceIndex,1);renderServices();updateCounts()});
function collectServices(){document.querySelectorAll('[data-service-index]').forEach(card=>{const item=content.services[+card.dataset.serviceIndex];card.querySelectorAll('[data-sfield]').forEach(input=>item[input.dataset.sfield]=clean(input.value,input.dataset.sfield==='desc'?220:80))})}
$('#addService').addEventListener('click',()=>{collectServices();content.services.push({id:Date.now(),cat:'consulting',icon:'✦',title:'خدمة جديدة',desc:'اكتب وصف الخدمة هنا.',color:'#e8f5fd'});renderServices();updateCounts()});
$('#saveServices').addEventListener('click',()=>{collectServices();save('تم نشر قائمة الخدمات')});

function renderVisibility(){$('#visibilityList').innerHTML=Object.entries(sectionNames).map(([key,label])=>`<label><span><b>${label}</b><small>${content.visibility[key]!==false?'ظاهر للزوار':'مخفي حاليًا'}</small></span><input type="checkbox" data-visibility="${key}" ${content.visibility[key]!==false?'checked':''}><i></i></label>`).join('')}
$('#saveVisibility').addEventListener('click',()=>{document.querySelectorAll('[data-visibility]').forEach(input=>content.visibility[input.dataset.visibility]=input.checked);save('تم تحديث الأقسام الظاهرة')});

start();
