const $=selector=>document.querySelector(selector);
const clean=(value,max=300)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max);
const esc=value=>clean(value,600).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const escLines=value=>String(value??'').replace(/[\u0000-\u0009\u000b-\u001f\u007f]/g,'').slice(0,20000).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let content=null;
const sectionNames={visualStory:'الصور والأنشطة الرئيسية',marquee:'شريط القطاعات المتحرك',saudiValue:'القيمة للسوق السعودي',method:'منهجية العمل والإنفوجرافيك',services:'مستكشف الخدمات',journey:'رحلة تنفيذ الخدمة',transformation:'المقارنة قبل وبعد',solutions:'حلول مراحل المنشأة',packages:'الباقات',eservices:'الخدمات الحكومية المنفردة',track:'تتبع الطلبات',knowledge:'مركز المعرفة',deliverables:'المخرجات والتسليمات',faq:'الأسئلة الشائعة',cta:'الدعوة الختامية للتواصل'};
const titles={overview:'نظرة عامة',content:'الهوية والمحتوى',media:'الصور والأنشطة',articles:'مركز المعرفة',services:'إدارة الخدمات',eservices:'الخدمات المنفردة',sections:'عرض الأقسام'};

async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{'content-type':'application/json','x-requested-with':'MadarAdmin',...(options.headers||{})}});const data=await response.json().catch(()=>({error:'استجابة غير صالحة'}));if(!response.ok)throw new Error(data.error||'تعذر إكمال العملية');return data}
function toast(message,type='ok'){$('#adminToast').textContent=message;$('#adminToast').className=`toast show ${type}`;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#adminToast').className='toast',2600)}
function setBusy(busy,label='جارٍ الحفظ…'){$('#saveState').textContent=busy?label:'تم الحفظ';document.body.classList.toggle('saving',busy)}

document.querySelectorAll('aside nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('aside nav button,.admin-page').forEach(x=>x.classList.remove('active'));button.classList.add('active');$('#'+button.dataset.page).classList.add('active');$('#pageTitle').textContent=titles[button.dataset.page]}));

async function start(){try{const session=await api('/api/admin/session',{method:'GET'});if(session.authenticated){$('#loginGate').classList.add('hidden');await loadContent()}else{$('#loginGate').classList.remove('hidden');if(!session.configured)$('#loginError').textContent='يلزم ضبط ADMIN_PASSWORD في إعدادات الخادم أولًا.'}}catch{$('#loginError').textContent='تعذر الاتصال بالخادم، حاول تحديث الصفحة.'}}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();$('#loginError').textContent='';const button=event.submitter;button.disabled=true;button.textContent='جارٍ التحقق…';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#passwordInput').value})});$('#passwordInput').value='';$('#loginGate').classList.add('hidden');await loadContent();toast('تم تسجيل الدخول بنجاح')}catch(error){$('#loginError').textContent=error.message}finally{button.disabled=false;button.textContent='دخول آمن'}});
$('#logoutBtn').addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST'})}finally{location.reload()}});

async function loadContent(){content=await api('/api/content',{method:'GET'});fillSettings();renderAll()}
function fillSettings(){const s=content.settings;$('#brandInput').value=s.brand;$('#colorInput').value=s.primary;$('#phoneInput').value=s.phone;$('#emailInput').value=s.email;$('#cityInput').value=s.city;$('#heroTitleInput').value=s.heroTitle;$('#heroSubtitleInput').value=s.heroSubtitle;$('#motionInput').value=s.motion;$('#motionLevelInput').value=s.motionLevel}
function renderAll(){renderActivities();renderArticles();renderServices();renderEntities();renderVisibility();updateCounts()}
function updateCounts(){$('#serviceCount').textContent=content.services.length;$('#activityCount').textContent=content.activities.length;$('#articleCount').textContent=content.articles.length;$('#sectionCount').textContent=Object.values(content.visibility).filter(Boolean).length}
async function save(message){setBusy(true);try{content=await api('/api/admin/content',{method:'PUT',body:JSON.stringify(content)});renderAll();toast(message)}catch(error){toast(error.message,'error');if(/تسجيل الدخول/.test(error.message))location.reload()}finally{setBusy(false)}}

$('#settingsForm').addEventListener('submit',event=>{event.preventDefault();content.settings={brand:clean($('#brandInput').value,40),primary:$('#colorInput').value,phone:clean($('#phoneInput').value,24),email:clean($('#emailInput').value,100),city:clean($('#cityInput').value,100),heroTitle:clean($('#heroTitleInput').value,140),heroSubtitle:clean($('#heroSubtitleInput').value,300),motion:$('#motionInput').value,motionLevel:$('#motionLevelInput').value};save('تم نشر إعدادات الهوية')});

function imageEditor(item,index,type){return `<article class="editor-card" data-index="${index}" data-type="${type}"><div class="editor-image"><img src="${esc(item.image)}" alt=""><label class="upload-btn">رفع صورة<input type="file" accept="image/jpeg,image/png,image/webp" data-upload></label><small>JPG أو PNG أو WebP — حتى 2MB</small></div><div class="editor-fields"><label>التصنيف<input data-field="tag" value="${esc(item.tag)}" maxlength="40"></label><label class="wide">العنوان<input data-field="title" value="${esc(item.title)}" maxlength="120"></label><label class="wide">الوصف<textarea data-field="desc" maxlength="260">${esc(item.desc)}</textarea></label><label class="wide">وصف الصورة لمحركات البحث<input data-field="alt" value="${esc(item.alt)}" maxlength="160"></label>${type==='article'?`<label class="wide">رابط المقال<input data-field="link" value="${esc(item.link||'#')}" maxlength="500" dir="ltr"></label>`:''}</div><button class="delete-editor" data-remove title="حذف">×</button></article>`}
function renderActivities(){$('#activityEditor').innerHTML=content.activities.map((x,i)=>imageEditor(x,i,'activity')).join('')||'<div class="empty">لا توجد أنشطة. أضف أول نشاط للبدء.</div>'}
function renderArticles(){$('#articleEditor').innerHTML=content.articles.map((x,i)=>imageEditor(x,i,'article')).join('')||'<div class="empty">لا توجد مقالات منشورة.</div>'}
function collectEditors(type){const key=type==='activity'?'activities':'articles';document.querySelectorAll(`[data-type="${type}"]`).forEach(card=>{const item=content[key][+card.dataset.index];card.querySelectorAll('[data-field]').forEach(input=>item[input.dataset.field]=clean(input.value,input.dataset.field==='desc'?260:input.dataset.field==='link'?500:160))})}
function bindEditor(container,type){container.addEventListener('change',async event=>{const input=event.target.closest('[data-upload]');if(!input)return;const file=input.files[0];if(!file)return;if(file.size>2_000_000)return toast('الصورة أكبر من 2MB','error');const card=input.closest('.editor-card'),button=card.querySelector('.upload-btn');button.classList.add('loading');button.childNodes[0].textContent='جارٍ الرفع…';try{const data=await fileToData(file),result=await api('/api/admin/upload',{method:'POST',body:JSON.stringify({data,name:file.name})});const key=type==='activity'?'activities':'articles';content[key][+card.dataset.index].image=result.url;card.querySelector('img').src=result.url;toast('تم رفع الصورة، اضغط حفظ للنشر')}catch(error){toast(error.message,'error')}finally{button.classList.remove('loading');button.childNodes[0].textContent='رفع صورة'}});container.addEventListener('click',event=>{const remove=event.target.closest('[data-remove]');if(!remove)return;collectEditors(type);const card=remove.closest('.editor-card'),key=type==='activity'?'activities':'articles';content[key].splice(+card.dataset.index,1);type==='activity'?renderActivities():renderArticles();updateCounts()})}
bindEditor($('#activityEditor'),'activity');bindEditor($('#articleEditor'),'article');
function fileToData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
$('#addActivity').addEventListener('click',()=>{collectEditors('activity');if(content.activities.length>=6)return toast('الحد الأقصى 6 أنشطة','error');content.activities.push({id:Date.now(),tag:'نشاط جديد',title:'عنوان النشاط',desc:'وصف مختصر للنشاط.',image:'assets/images/saudi-business-establishment.svg',alt:'صورة نشاط أعمال'});renderActivities();updateCounts()});
$('#addArticle').addEventListener('click',()=>{collectEditors('article');if(content.articles.length>=9)return toast('الحد الأقصى 9 مقالات','error');content.articles.push({id:Date.now(),tag:'مقال',title:'عنوان المقال الجديد',desc:'نبذة مختصرة عن محتوى المقال.',image:'assets/images/company-formation.svg',alt:'صورة المقال',link:'#'});renderArticles();updateCounts()});
$('#saveActivities').addEventListener('click',()=>{collectEditors('activity');save('تم نشر الصور والأنشطة')});
$('#saveArticles').addEventListener('click',()=>{collectEditors('article');save('تم نشر مركز المعرفة')});

function renderServices(){$('#serviceAdminList').innerHTML=content.services.map((s,i)=>`<article class="service-item" data-service-index="${i}"><i style="background:${esc(s.color)}">${esc(s.icon)}</i><div><label>اسم الباقة<input data-sfield="title" value="${esc(s.title)}" maxlength="80"></label><label>الوصف<textarea data-sfield="desc" maxlength="220">${esc(s.desc)}</textarea></label><div class="service-extra"><label>الفئة المناسبة<input data-sfield="audience" value="${esc(s.audience||'')}" maxlength="80"></label><label>المدة<input data-sfield="duration" value="${esc(s.duration||'')}" maxlength="40"></label><label>السعر<input data-sfield="price" value="${esc(s.price||'')}" maxlength="40"></label></div><label>الخدمات والمنصات المشمولة<textarea class="features-input" data-sfield="features" maxlength="900" placeholder="اكتب كل عنصر في سطر">${escLines(Array.isArray(s.features)?s.features.join('\n'):'')}</textarea></label><span><select data-sfield="cat"><option value="startup" ${s.cat==='startup'?'selected':''}>التأسيس</option><option value="government" ${s.cat==='government'?'selected':''}>باقات المنشآت</option><option value="consulting" ${s.cat==='consulting'?'selected':''}>المستثمرون</option><option value="growth" ${s.cat==='growth'?'selected':''}>الاستشارات</option></select><input class="icon-input" data-sfield="icon" value="${esc(s.icon)}" maxlength="3" title="الرمز"><input type="color" data-sfield="color" value="${esc(s.color)}" title="لون البطاقة"></span></div><button data-delete-service title="حذف">×</button></article>`).join('')||'<div class="empty">لا توجد خدمات حاليًا.</div>'}
$('#serviceAdminList').addEventListener('click',event=>{const button=event.target.closest('[data-delete-service]');if(!button)return;collectServices();content.services.splice(+button.closest('[data-service-index]').dataset.serviceIndex,1);renderServices();updateCounts()});
function collectServices(){document.querySelectorAll('[data-service-index]').forEach(card=>{const item=content.services[+card.dataset.serviceIndex];card.querySelectorAll('[data-sfield]').forEach(input=>{const field=input.dataset.sfield;if(field==='features')item.features=String(input.value).split(/\r?\n|،/).map(value=>clean(value,80)).filter(Boolean).slice(0,12);else item[field]=clean(input.value,field==='desc'?220:field==='duration'||field==='price'?40:80)})})}
$('#addService').addEventListener('click',()=>{collectServices();content.services.push({id:Date.now(),cat:'growth',icon:'✦',title:'باقة جديدة',desc:'اكتب وصف الباقة هنا.',audience:'',duration:'',price:'',features:[],color:'#e8f5fd'});renderServices();updateCounts()});
$('#saveServices').addEventListener('click',()=>{collectServices();save('تم نشر قائمة الخدمات')});

function renderVisibility(){$('#visibilityList').innerHTML=Object.entries(sectionNames).map(([key,label])=>`<label><span><b>${label}</b><small>${content.visibility[key]!==false?'ظاهر للزوار':'مخفي حاليًا'}</small></span><input type="checkbox" data-visibility="${key}" ${content.visibility[key]!==false?'checked':''}><i></i></label>`).join('')}
$('#saveVisibility').addEventListener('click',()=>{document.querySelectorAll('[data-visibility]').forEach(input=>content.visibility[input.dataset.visibility]=input.checked);save('تم تحديث الأقسام الظاهرة')});

start();

// الخدمات الحكومية المنفردة حسب الجهة
function entityLines(key){return (content.govServices||[]).filter(s=>s.entity===key).map(s=>s.price?`${s.title} | ${s.price}`:s.title).join('\n')}
function renderEntities(){content.entities=content.entities||[];content.govServices=content.govServices||[];const q=clean($('#esFilter').value,40);$('#entityAdminList').innerHTML=content.entities.map((e,i)=>`<article class="service-item entity-item" data-entity-index="${i}" ${q&&!e.name.includes(q)?'hidden':''}><i style="background:${esc(e.color)}">${esc(e.icon)}</i><div><div class="service-extra"><label>اسم الجهة<input data-efield="name" value="${esc(e.name)}" maxlength="60"></label><label>الرمز<input data-efield="icon" value="${esc(e.icon)}" maxlength="4"></label><label>اللون<input type="color" data-efield="color" value="${esc(e.color)}"></label></div><label>وصف مختصر<input data-efield="desc" value="${esc(e.desc||'')}" maxlength="200"></label><label>الخدمات (${(content.govServices.filter(s=>s.entity===e.key)).length}) — سطر لكل خدمة: الاسم | السعر<textarea class="features-input entity-lines" data-efield="lines" rows="8">${escLines(entityLines(e.key))}</textarea></label></div><button data-delete-entity title="حذف الجهة وخدماتها">×</button></article>`).join('')||'<div class="empty">لا توجد جهات بعد.</div>';$('#esAdminCount').textContent=`${content.entities.length} جهة · ${content.govServices.length} خدمة`}
function collectEntities(){const kept=[];let seq=Date.now();document.querySelectorAll('[data-entity-index]').forEach(card=>{const e=content.entities[+card.dataset.entityIndex];card.querySelectorAll('[data-efield]').forEach(input=>{const f=input.dataset.efield;if(f!=='lines')e[f]=clean(input.value,f==='desc'?200:f==='name'?60:f==='icon'?4:7)});const lines=String(card.querySelector('[data-efield="lines"]').value).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const old=content.govServices.filter(s=>s.entity===e.key);lines.forEach(line=>{const [title,price='']=line.split('|').map(x=>clean(x,100));if(!title)return;const prev=old.find(s=>s.title===title);kept.push({id:prev?prev.id:seq++,entity:e.key,title,price:clean(price,30)})})});content.govServices=kept}
$('#esFilter').addEventListener('input',()=>{collectEntities();renderEntities()});
$('#entityAdminList').addEventListener('click',event=>{const b=event.target.closest('[data-delete-entity]');if(!b)return;collectEntities();const e=content.entities[+b.closest('[data-entity-index]').dataset.entityIndex];if(!confirm(`حذف «${e.name}» وجميع خدماتها؟`))return;content.entities=content.entities.filter(x=>x!==e);content.govServices=content.govServices.filter(s=>s.entity!==e.key);renderEntities()});
$('#addEntity').addEventListener('click',()=>{collectEntities();content.entities.unshift({key:'e'+Date.now().toString(36),name:'جهة جديدة',icon:'✦',color:'#e8f5fd',desc:''});$('#esFilter').value='';renderEntities()});
$('#saveEntities').addEventListener('click',()=>{collectEntities();save('تم نشر الخدمات المنفردة')});
