const services=[
{id:1,cat:'startup',icon:'▦',title:'تأسيس الشركات',desc:'من اختيار الكيان حتى إصدار السجل وتجهيز المنشأة للتشغيل.',color:'#e5f5ff'},
{id:2,cat:'government',icon:'⌁',title:'الخدمات الحكومية',desc:'تنفيذ ومتابعة معاملات المنشأة عبر الجهات والمنصات ذات العلاقة.',color:'#e8f9f5'},
{id:3,cat:'government',icon:'٪',title:'الزكاة والضريبة',desc:'خدمات التسجيل والإقرارات والمتابعة المحاسبية للمنشآت.',color:'#fff5dd'},
{id:4,cat:'government',icon:'♙',title:'الموارد البشرية',desc:'خدمات قوى ومدد والتأمينات وتنظيم دورة حياة الموظف.',color:'#f0edff'},
{id:5,cat:'consulting',icon:'◎',title:'دراسات الجدوى',desc:'دراسة السوق والجوانب الفنية والمالية قبل قرار الاستثمار.',color:'#e5f8f8'},
{id:6,cat:'consulting',icon:'⌘',title:'الحوكمة والامتثال',desc:'أطر واضحة للصلاحيات والسياسات والمخاطر واستدامة القرار.',color:'#eaf0ff'},
{id:7,cat:'growth',icon:'↗',title:'التخطيط ومؤشرات الأداء',desc:'تحويل الرؤية إلى أهداف ومبادرات ومؤشرات قابلة للقياس.',color:'#e7f8f1'},
{id:8,cat:'growth',icon:'✓',title:'الجودة وشهادات ISO',desc:'تحليل الفجوات وبناء الأنظمة والتأهيل لمتطلبات الجودة.',color:'#eaf7ff'},
{id:9,cat:'government',icon:'⌂',title:'التراخيص البلدية والسلامة',desc:'إصدار وتجديد التراخيص ومتابعة متطلبات السلامة.',color:'#fff2e8'},
{id:10,cat:'growth',icon:'◈',title:'التحول الرقمي',desc:'أتمتة الإجراءات وربط البيانات وبناء لوحات قيادة للأعمال.',color:'#e9f5ff'},
{id:11,cat:'startup',icon:'◇',title:'خدمات المستثمرين',desc:'مسار تأسيس منظم للمستثمر السعودي والخليجي والأجنبي.',color:'#eef9e9'},
{id:12,cat:'government',icon:'®',title:'الملكية الفكرية',desc:'تسجيل العلامات التجارية ومتابعة الطلبات وحماية الأصول.',color:'#f7edff'}
];
const stages={idea:{n:'01',title:'حوّل الفكرة إلى قرار واضح',desc:'نختبر جدوى الفكرة ونحدّد نموذج العمل والمتطلبات قبل الالتزام بالتكاليف.',items:['دراسة جدوى أولية','تحليل السوق والمنافسين','اختيار نموذج العمل','خريطة التأسيس']},launch:{n:'02',title:'أسّس كيانك على أساس سليم',desc:'ننسّق خطوات التأسيس والتراخيص ونجهزك للانتقال إلى التشغيل.',items:['اختيار الكيان القانوني','إجراءات السجل والتأسيس','التراخيص اللازمة','ملف جاهزية التشغيل']},operate:{n:'03',title:'شغّل منشأتك بوضوح وانضباط',desc:'نرتّب الالتزامات الحكومية والموارد البشرية والعمليات اليومية.',items:['إدارة المنصات الحكومية','سياسات الموارد البشرية','التقويم النظامي','إجراءات التشغيل']},scale:{n:'04',title:'ابنِ منظومة قابلة للنمو',desc:'نربط الاستراتيجية بالحوكمة والعمليات والمؤشرات لتوسّع أكثر ثباتًا.',items:['خطة استراتيجية','مؤشرات أداء KPI','حوكمة وصلاحيات','تحول رقمي وجودة']}};
const grid=document.getElementById('servicesGrid');
function renderServices(filter='all',term=''){const q=term.trim().toLowerCase();const rows=services.filter(s=>(filter==='all'||s.cat===filter)&&(!q||(`${s.title} ${s.desc}`).toLowerCase().includes(q)));grid.innerHTML=rows.map(s=>`<article class="service-card reveal visible" style="--card-color:${s.color}"><span class="service-icon">${s.icon}</span><h3>${s.title}</h3><p>${s.desc}</p><a href="#" data-service="${s.title}">استكشف الخدمة ←</a></article>`).join('');document.getElementById('noResults').hidden=rows.length>0;}
renderServices();
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderServices(b.dataset.filter,document.getElementById('serviceSearch').value)});
document.getElementById('serviceSearch').addEventListener('input',e=>renderServices(document.querySelector('.filters .active').dataset.filter,e.target.value));
document.getElementById('searchBtn').onclick=()=>renderServices(document.querySelector('.filters .active').dataset.filter,document.getElementById('serviceSearch').value);
const panel=document.getElementById('stagePanel');function showStage(key){const s=stages[key];panel.innerHTML=`<span class="stage-number">${s.n}</span><h3>${s.title}</h3><p>${s.desc}</p><div class="stage-list">${s.items.map(x=>`<span>${x}</span>`).join('')}</div>`;}showStage('idea');document.querySelectorAll('#stageTabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#stageTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');showStage(b.dataset.stage)});
const reveals=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});reveals.forEach(el=>observer.observe(el));
addEventListener('scroll',()=>document.getElementById('header').classList.toggle('scrolled',scrollY>10));
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('nav');menu.onclick=()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const modal=document.getElementById('wizardModal');let step=1;const form=document.getElementById('requestForm');function updateWizard(){document.querySelectorAll('.wizard-step').forEach(x=>x.classList.toggle('active',+x.dataset.step===step));document.getElementById('stepCount').textContent=`${step} / 4`;document.getElementById('wizardProgress').style.width=`${step*25}%`;document.getElementById('prevStep').hidden=step===1||step===4;const next=document.getElementById('nextStep');next.hidden=step===4;next.innerHTML=step===3?'إرسال الطلب <span>←</span>':'التالي <span>←</span>';}
function openWizard(service=''){step=1;form.reset();if(service){const select=form.elements.service;[...select.options].forEach(o=>{if(o.text.includes(service)||service.includes(o.text))o.selected=true})}updateWizard();modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeWizard(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.querySelectorAll('.open-wizard').forEach(b=>b.onclick=()=>openWizard());modal.querySelector('.modal-close').onclick=closeWizard;modal.querySelector('.modal-backdrop').onclick=closeWizard;
grid.addEventListener('click',e=>{const a=e.target.closest('[data-service]');if(a){e.preventDefault();openWizard(a.dataset.service)}});
document.getElementById('nextStep').onclick=()=>{if(step===1&&!form.elements.customer.value)return toast('اختر صفة العميل للمتابعة');if(step===2&&!form.elements.service.value)return toast('اختر نوع الخدمة للمتابعة');if(step===3){if(!form.elements.name.value||!form.elements.phone.value)return toast('أدخل الاسم ورقم الجوال');document.getElementById('generatedId').textContent='MD-'+Math.floor(1000+Math.random()*8999);}step=Math.min(4,step+1);updateWizard()};document.getElementById('prevStep').onclick=()=>{step=Math.max(1,step-1);updateWizard()};
const dash=document.getElementById('dashboardModal');document.getElementById('demoDashboard').onclick=()=>{dash.classList.add('open');dash.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};function closeDash(){dash.classList.remove('open');document.body.style.overflow=''};dash.querySelector('.dash-close').onclick=closeDash;dash.querySelector('.modal-backdrop').onclick=closeDash;
document.getElementById('trackBtn').onclick=()=>{const val=document.getElementById('trackInput').value.trim().toUpperCase();if(!val)return toast('أدخل رقم الطلب');if(val==='MD-2048')toast('تم العثور على الطلب وتحديث حالته');else toast('نسخة العرض تدعم الطلب MD-2048 فقط')};
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeWizard();closeDash()}});
