const defaultServices=[
{id:101,cat:'startup',icon:'▦',title:'باقة التأسيس',desc:'إدارة الخدمات الحكومية للمنشأة منذ التأسيس خلال أول ثلاثة أشهر.',audience:'من 1 إلى 4 موظفين',duration:'3 أشهر',price:'4,500 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية','البريد السعودي'],color:'#e5f5ff'},
{id:102,cat:'consulting',icon:'◇',title:'باقة المستثمر الأجنبي',desc:'مسار تأسيس ومتابعة للخدمات الحكومية المخصصة للمستثمر الأجنبي داخل المملكة.',audience:'المستثمر الأجنبي',duration:'3 أشهر',price:'18,000 ر.س',features:['وزارة الاستثمار','وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية'],color:'#eef0ff'},
{id:103,cat:'consulting',icon:'◈',title:'باقة المستثمر الخليجي',desc:'متابعة إجراءات التأسيس والمنصات الحكومية للمستثمر الخليجي خلال مرحلة الانطلاق.',audience:'المستثمر الخليجي',duration:'3 أشهر',price:'6,000 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية','البريد السعودي'],color:'#e8f9f5'},
{id:104,cat:'government',icon:'B',title:'الباقة البرونزية',desc:'إدارة دورية للمنصات الحكومية الأساسية للمنشآت الصغيرة ضمن نطاق تشغيلي واضح.',audience:'من 5 إلى 14 موظفًا',duration:'3 أشهر',price:'2,940 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','الغرف التجارية','أبشر أعمال والجوازات','التأمينات الاجتماعية','العنوان الوطني'],color:'#fff1e4'},
{id:105,cat:'government',icon:'S',title:'الباقة الفضية',desc:'متابعة موسعة للمنصات الحكومية تناسب المنشآت التي تنمو في عدد الموظفين والالتزامات.',audience:'من 15 إلى 29 موظفًا',duration:'3 أشهر',price:'5,220 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','الغرف التجارية','أبشر أعمال والجوازات','التأمينات الاجتماعية','العنوان الوطني'],color:'#edf3f7'},
{id:106,cat:'government',icon:'G',title:'الباقة الذهبية',desc:'إدارة متقدمة للمنصات الحكومية للمنشآت المتوسطة مع حجم عمليات والتزامات أكبر.',audience:'من 30 إلى 49 موظفًا',duration:'3 أشهر',price:'7,350 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','الغرف التجارية','أبشر أعمال والجوازات','التأمينات الاجتماعية','العنوان الوطني'],color:'#fff5dd'},
{id:107,cat:'government',icon:'◆',title:'الباقة الماسية',desc:'إدارة شاملة للمنصات الحكومية للمنشآت الأكبر مع متابعة أكثر اتساعًا للاحتياجات التشغيلية.',audience:'حتى 99 موظفًا',duration:'3 أشهر',price:'11,880 ر.س',features:['وزارة الاستثمار','وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية'],color:'#e9f7ff'},
{id:108,cat:'government',icon:'P',title:'الباقة البلاتينية',desc:'مستوى متابعة موسع للمنشآت ذات الاحتياج الحكومي والتشغيلي الكبير.',audience:'منشآت ذات تشغيل موسع',duration:'3 أشهر',price:'18,000 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية','البريد السعودي'],color:'#eeeaff'},
{id:109,cat:'growth',icon:'◎',title:'استشارة خاصة في الخدمات الحكومية',desc:'جلسة متخصصة لفهم الحالة وتحديد المسار الأنسب للتعامل مع الخدمة الحكومية المطلوبة.',audience:'الأفراد والمنشآت',duration:'جلسة خاصة',price:'199 ر.س',features:['تشخيص الاحتياج','تحديد الجهة والمنصة','مراجعة المتطلبات','توضيح خطوات التنفيذ'],color:'#e7f8f1'}
];
function safeParse(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
function cleanText(value,max=180){return String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max)}
function escapeHTML(value){return cleanText(value,500).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function safeColor(value){return /^#[0-9a-f]{6}$/i.test(String(value))?String(value):'#e8f5fd'}
function normalizeService(s,index){return{id:Number.isFinite(+s?.id)?+s.id:index+1,cat:['startup','government','consulting','growth'].includes(s?.cat)?s.cat:'consulting',icon:cleanText(s?.icon||'✦',3),title:cleanText(s?.title||'خدمة أعمال',80),desc:cleanText(s?.desc||'',220),audience:cleanText(s?.audience||'',80),duration:cleanText(s?.duration||'',40),price:cleanText(s?.price||'',40),features:(Array.isArray(s?.features)?s.features:[]).slice(0,12).map(x=>cleanText(x,80)).filter(Boolean),color:safeColor(s?.color)}}
const savedServices=safeParse('madar_services',null);
let services=(Array.isArray(savedServices)&&savedServices.length?savedServices:defaultServices).slice(0,100).map(normalizeService);
const siteSettings=safeParse('madar_settings',{});
if(siteSettings.brand){document.querySelectorAll('.brand b').forEach(x=>x.textContent=cleanText(siteSettings.brand,40))}
if(safeColor(siteSettings.primary)===siteSettings.primary){document.documentElement.style.setProperty('--blue',siteSettings.primary)}
if(siteSettings.heroTitle){const title=document.getElementById('heroTitle'),parts=cleanText(siteSettings.heroTitle,140).split('|');title.replaceChildren(document.createTextNode(parts.shift()||''));if(parts.length){title.append(document.createElement('br'));const em=document.createElement('em');em.textContent=parts.join(' ').trim();title.append(em)}}
if(siteSettings.heroSubtitle){document.getElementById('heroSubtitle').textContent=siteSettings.heroSubtitle}
if(siteSettings.motion==='off')document.body.classList.add('motion-off');
if(siteSettings.motionLevel==='rich')document.body.classList.add('motion-rich');
const stages={idea:{n:'01',title:'حوّل الفكرة إلى قرار واضح',desc:'نختبر جدوى الفكرة ونحدّد نموذج العمل والمتطلبات قبل الالتزام بالتكاليف.',items:['دراسة جدوى أولية','تحليل السوق والمنافسين','اختيار نموذج العمل','خريطة التأسيس']},launch:{n:'02',title:'أسّس كيانك على أساس سليم',desc:'ننسّق خطوات التأسيس والتراخيص ونجهزك للانتقال إلى التشغيل.',items:['اختيار الكيان القانوني','إجراءات السجل والتأسيس','التراخيص اللازمة','ملف جاهزية التشغيل']},operate:{n:'03',title:'شغّل منشأتك بوضوح وانضباط',desc:'نرتّب الالتزامات الحكومية والموارد البشرية والعمليات اليومية.',items:['إدارة المنصات الحكومية','سياسات الموارد البشرية','التقويم النظامي','إجراءات التشغيل']},scale:{n:'04',title:'ابنِ منظومة قابلة للنمو',desc:'نربط الاستراتيجية بالحوكمة والعمليات والمؤشرات لتوسّع أكثر ثباتًا.',items:['خطة استراتيجية','مؤشرات أداء KPI','حوكمة وصلاحيات','تحول رقمي وجودة']}};
const grid=document.getElementById('servicesGrid');
function renderServices(filter='all',term=''){const q=cleanText(term,80).toLowerCase();const rows=services.filter(s=>(filter==='all'||s.cat===filter)&&(!q||(`${s.title} ${s.desc} ${s.audience} ${s.features.join(' ')}`).toLowerCase().includes(q)));grid.innerHTML=rows.map(s=>`<article class="service-card reveal visible" style="--card-color:${safeColor(s.color)}"><div class="service-card-top"><span class="service-icon">${escapeHTML(s.icon)}</span>${s.price?`<strong>${escapeHTML(s.price)}</strong>`:''}</div><h3>${escapeHTML(s.title)}</h3>${s.audience?`<span class="service-audience">${escapeHTML(s.audience)}</span>`:''}<p>${escapeHTML(s.desc)}</p><div class="service-meta">${s.duration?`<span>◷ ${escapeHTML(s.duration)}</span>`:''}<span>${s.features.length} عناصر ضمن النطاق</span></div><a href="#" data-service="${escapeHTML(s.title)}">عرض تفاصيل الباقة ←</a></article>`).join('');document.getElementById('noResults').hidden=rows.length>0;}
function syncServiceOptions(){const select=document.querySelector('#requestForm select[name="service"]');if(!select)return;const current=select.value;select.replaceChildren(new Option('اختر الباقة أو الخدمة',''));services.forEach(service=>select.add(new Option(service.title,service.title)));select.add(new Option('لست متأكدًا','لست متأكدًا'));if([...select.options].some(option=>option.value===current))select.value=current}
renderServices();
syncServiceOptions();
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderServices(b.dataset.filter,document.getElementById('serviceSearch').value)});
document.getElementById('serviceSearch').addEventListener('input',e=>renderServices(document.querySelector('.filters .active').dataset.filter,e.target.value));
document.getElementById('searchBtn').onclick=()=>renderServices(document.querySelector('.filters .active').dataset.filter,document.getElementById('serviceSearch').value);
const panel=document.getElementById('stagePanel');function showStage(key){const s=stages[key];panel.innerHTML=`<span class="stage-number">${s.n}</span><h3>${s.title}</h3><p>${s.desc}</p><div class="stage-list">${s.items.map(x=>`<span>${x}</span>`).join('')}</div>`;}showStage('idea');document.querySelectorAll('#stageTabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#stageTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');showStage(b.dataset.stage)});
const reveals=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});reveals.forEach(el=>observer.observe(el));
const counters=document.querySelectorAll('.counter');const counterObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting||entry.target.dataset.done)return;entry.target.dataset.done='1';const el=entry.target,target=+el.dataset.count,suffix=el.dataset.suffix||'',started=performance.now();function tick(now){const p=Math.min(1,(now-started)/1100),value=Math.round(target*(1-Math.pow(1-p,3)));el.textContent=value+suffix;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}),{threshold:.6});counters.forEach(x=>counterObserver.observe(x));
addEventListener('scroll',()=>document.getElementById('header').classList.toggle('scrolled',scrollY>10));
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('nav');menu.onclick=()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const modal=document.getElementById('wizardModal');let step=1;const form=document.getElementById('requestForm');function updateWizard(){document.querySelectorAll('.wizard-step').forEach(x=>x.classList.toggle('active',+x.dataset.step===step));document.getElementById('stepCount').textContent=`${step} / 4`;document.getElementById('wizardProgress').style.width=`${step*25}%`;document.getElementById('prevStep').hidden=step===1||step===4;const next=document.getElementById('nextStep');next.hidden=step===4;next.innerHTML=step===3?'إرسال الطلب <span>←</span>':'التالي <span>←</span>';}
function openWizard(service=''){step=1;form.reset();if(service){const select=form.elements.service;[...select.options].forEach(o=>{if(o.text.includes(service)||service.includes(o.text))o.selected=true})}updateWizard();modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeWizard(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.querySelectorAll('.open-wizard').forEach(b=>b.onclick=()=>openWizard());modal.querySelector('.modal-close').onclick=closeWizard;modal.querySelector('.modal-backdrop').onclick=closeWizard;
const serviceModal=document.getElementById('serviceModal');let selectedService='';
function openService(title){const s=services.find(x=>x.title===title);if(!s)return;selectedService=s.title;document.getElementById('detailIcon').textContent=s.icon;document.getElementById('detailTitle').textContent=s.title;document.getElementById('detailDesc').textContent=s.desc;document.getElementById('detailAudience').textContent=s.audience||'حسب احتياج المنشأة';document.getElementById('detailDuration').textContent=s.duration||'تحدد بعد المراجعة';document.getElementById('detailPrice').textContent=s.price||'عرض مخصص';document.getElementById('detailPoints').innerHTML=(s.features.length?s.features:['مراجعة أولية للاحتياج','تحديد المتطلبات بوضوح','متابعة رقمية لكل مرحلة']).map(x=>`<span>✓ ${escapeHTML(x)}</span>`).join('');serviceModal.classList.add('open');serviceModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeService(){serviceModal.classList.remove('open');serviceModal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
grid.addEventListener('click',e=>{const a=e.target.closest('[data-service]');if(a){e.preventDefault();openService(a.dataset.service)}});serviceModal.querySelector('.service-close').onclick=closeService;serviceModal.querySelector('.modal-backdrop').onclick=closeService;serviceModal.querySelector('.detail-order').onclick=()=>{closeService();openWizard(selectedService)};
document.getElementById('nextStep').onclick=()=>{if(step===1&&!form.elements.customer.value)return toast('اختر صفة العميل للمتابعة');if(step===2&&!form.elements.service.value)return toast('اختر نوع الخدمة للمتابعة');if(step===3){const name=cleanText(form.elements.name.value,80),phone=form.elements.phone.value.replace(/[\s()-]/g,'');if(name.length<2)return toast('أدخل اسمًا صحيحًا');if(!/^(?:\+?966|0)?5\d{8}$/.test(phone))return toast('أدخل رقم جوال سعودي صحيحًا');form.elements.name.value=name;document.getElementById('generatedId').textContent='MD-'+crypto.getRandomValues(new Uint32Array(1))[0].toString().slice(0,4).padEnd(4,'0');}step=Math.min(4,step+1);updateWizard()};document.getElementById('prevStep').onclick=()=>{step=Math.max(1,step-1);updateWizard()};
const dash=document.getElementById('dashboardModal');document.getElementById('demoDashboard').onclick=()=>{dash.classList.add('open');dash.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};function closeDash(){dash.classList.remove('open');document.body.style.overflow=''};dash.querySelector('.dash-close').onclick=closeDash;dash.querySelector('.modal-backdrop').onclick=closeDash;
document.getElementById('trackBtn').onclick=()=>{const val=document.getElementById('trackInput').value.trim().toUpperCase();if(!val)return toast('أدخل رقم الطلب');if(val==='MD-2048')toast('تم العثور على الطلب وتحديث حالته');else toast('نسخة العرض تدعم الطلب MD-2048 فقط')};
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeWizard();closeDash();closeService()}});
const progressBar=document.getElementById('scrollProgress'),backTop=document.getElementById('backTop');
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progressBar.style.width=`${max?scrollY/max*100:0}%`;backTop.classList.toggle('show',scrollY>650)});backTop.onclick=()=>scrollTo({top:0,behavior:'smooth'});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(800px) rotateY(${x*4}deg) rotateX(${-y*4}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}

// محتوى مركزي قادم من لوحة الإدارة. تبقى القيم المضمّنة بديلًا آمنًا عند تعذر الاتصال.
const cmsSectionSelectors={visualStory:'.visual-story',marquee:'.sector-marquee',saudiValue:'.saudi-value',method:'#method',services:'#services',journey:'#journey',transformation:'.transformation',solutions:'#solutions',packages:'#packages',track:'#track',knowledge:'#knowledge',deliverables:'.deliverables',faq:'#faq',cta:'#about'};
function applyCMS(data){
  if(!data||typeof data!=='object')return;
  const settings=data.settings||{};
  if(settings.brand)document.querySelectorAll('.brand b').forEach(x=>x.textContent=cleanText(settings.brand,40));
  if(/^#[0-9a-f]{6}$/i.test(settings.primary||''))document.documentElement.style.setProperty('--blue',settings.primary);
  if(settings.heroTitle){const title=document.getElementById('heroTitle'),parts=cleanText(settings.heroTitle,140).split('|');title.replaceChildren(document.createTextNode(parts.shift()||''));if(parts.length){title.append(document.createElement('br'));const em=document.createElement('em');em.textContent=parts.join(' ').trim();title.append(em)}}
  if(settings.heroSubtitle)document.getElementById('heroSubtitle').textContent=cleanText(settings.heroSubtitle,300);
  document.body.classList.toggle('motion-off',settings.motion==='off');document.body.classList.toggle('motion-rich',settings.motionLevel==='rich');
  if(settings.phone){const digits=settings.phone.replace(/\D/g,'');document.querySelectorAll('a[href^="tel:"]').forEach(a=>{a.href='tel:+'+digits;a.textContent=settings.phone});document.querySelectorAll('a[href^="https://wa.me/"]').forEach(a=>a.href='https://wa.me/'+digits)}
  if(settings.email)document.querySelectorAll('a[href^="mailto:"]').forEach(a=>{a.href='mailto:'+settings.email;a.textContent=settings.email});
  if(settings.city){const contact=document.querySelector('.footer-grid>div:last-child p');if(contact)contact.textContent=settings.city}
  Object.entries(cmsSectionSelectors).forEach(([key,selector])=>{const section=document.querySelector(selector);if(section)section.hidden=data.visibility?.[key]===false});
  if(Array.isArray(data.activities)&&data.activities.length){const visual=document.querySelector('.visual-grid');visual.innerHTML=data.activities.map((item,index)=>`<article class="visual-card ${index===0?'visual-wide ':''}visible tilt"><img src="${escapeHTML(item.image)}" alt="${escapeHTML(item.alt||item.title)}" loading="lazy" width="${index===0?1600:1000}" height="${index===0?1000:700}"><div><span>${escapeHTML(item.tag)}</span><h3>${escapeHTML(item.title)}</h3>${item.desc?`<p>${escapeHTML(item.desc)}</p>`:''}</div></article>`).join('')}
  if(Array.isArray(data.articles)&&data.articles.length){const articles=document.querySelector('.articles');articles.innerHTML=data.articles.map(item=>`<article class="article visible"><span>${escapeHTML(item.tag)}</span><div class="article-art"><img src="${escapeHTML(item.image)}" alt="${escapeHTML(item.alt||item.title)}" loading="lazy" width="1000" height="700"></div><h3>${escapeHTML(item.title)}</h3><p>${escapeHTML(item.desc)}</p><a href="${escapeHTML(item.link||'#')}">اقرأ المقال ←</a></article>`).join('')}
  if(Array.isArray(data.services)){services=data.services.slice(0,100).map(normalizeService);renderServices(document.querySelector('.filters .active')?.dataset.filter||'all',document.getElementById('serviceSearch').value);syncServiceOptions()}
}
fetch('/api/content',{headers:{accept:'application/json'}}).then(response=>response.ok?response.json():Promise.reject()).then(applyCMS).catch(()=>{});
