const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const root = __dirname;
const port = Number(process.env.PORT || 3000);
const dataDir = path.resolve(process.env.DATA_DIR || path.join(root, 'storage'));
const uploadsDir = path.join(dataDir, 'uploads');
const contentFile = path.join(dataDir, 'content.json');
const adminPassword = String(process.env.ADMIN_PASSWORD || '');
fs.mkdirSync(uploadsDir, {recursive:true});

const defaultServices=[
  {id:101,cat:'startup',icon:'▦',title:'باقة التأسيس',desc:'إدارة الخدمات الحكومية للمنشأة منذ التأسيس خلال أول ثلاثة أشهر.',audience:'من 1 إلى 4 موظفين',duration:'3 أشهر',price:'4,500 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية','البريد السعودي'],color:'#e5f5ff'},
  {id:102,cat:'consulting',icon:'◇',title:'باقة المستثمر الأجنبي',desc:'مسار تأسيس ومتابعة للخدمات الحكومية المخصصة للمستثمر الأجنبي داخل المملكة.',audience:'المستثمر الأجنبي',duration:'3 أشهر',price:'18,000 ر.س',features:['وزارة الاستثمار','وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية'],color:'#eef0ff'},
  {id:103,cat:'consulting',icon:'◈',title:'باقة المستثمر الخليجي',desc:'متابعة إجراءات التأسيس والمنصات الحكومية للمستثمر الخليجي خلال مرحلة الانطلاق.',audience:'المستثمر الخليجي',duration:'3 أشهر',price:'6,000 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية','البريد السعودي'],color:'#e8f9f5'},
  {id:104,cat:'government',icon:'B',title:'الباقة البرونزية',desc:'إدارة دورية للمنصات الحكومية الأساسية للمنشآت الصغيرة ضمن نطاق تشغيلي واضح.',audience:'من 5 إلى 14 موظفًا',duration:'3 أشهر',price:'2,940 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','الغرف التجارية','أبشر أعمال والجوازات','التأمينات الاجتماعية','العنوان الوطني'],color:'#fff1e4'},
  {id:105,cat:'government',icon:'S',title:'الباقة الفضية',desc:'متابعة موسعة للمنصات الحكومية تناسب المنشآت التي تنمو في عدد الموظفين والالتزامات.',audience:'من 15 إلى 29 موظفًا',duration:'3 أشهر',price:'5,220 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','الغرف التجارية','أبشر أعمال والجوازات','التأمينات الاجتماعية','العنوان الوطني'],color:'#edf3f7'},
  {id:106,cat:'government',icon:'G',title:'الباقة الذهبية',desc:'إدارة متقدمة للمنصات الحكومية للمنشآت المتوسطة مع حجم عمليات والتزامات أكبر.',audience:'من 30 إلى 49 موظفًا',duration:'3 أشهر',price:'7,350 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','الغرف التجارية','أبشر أعمال والجوازات','التأمينات الاجتماعية','العنوان الوطني'],color:'#fff5dd'},
  {id:107,cat:'government',icon:'◆',title:'الباقة الماسية',desc:'إدارة شاملة للمنصات الحكومية للمنشآت الأكبر مع متابعة أكثر اتساعًا للاحتياجات التشغيلية.',audience:'حتى 99 موظفًا',duration:'3 أشهر',price:'11,880 ر.س',features:['وزارة الاستثمار','وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية'],color:'#e9f7ff'},
  {id:108,cat:'government',icon:'P',title:'الباقة البلاتينية',desc:'مستوى متابعة موسع للمنشآت ذات الاحتياج الحكومي والتشغيلي الكبير.',audience:'منشآت ذات تشغيل موسع',duration:'3 أشهر',price:'18,000 ر.س',features:['وزارة التجارة','منصة بلدي','الدفاع المدني','منصة مدد','منصة قوى','هيئة الزكاة','مكتب العمل','الجوازات','التأمينات الاجتماعية','البريد السعودي'],color:'#eeeaff'},
  {id:109,cat:'growth',icon:'◎',title:'استشارة خاصة في الخدمات الحكومية',desc:'جلسة متخصصة لفهم الحالة وتحديد المسار الأنسب للتعامل مع الخدمة الحكومية المطلوبة.',audience:'الأفراد والمنشآت',duration:'جلسة خاصة',price:'199 ر.س',features:['تشخيص الاحتياج','تحديد الجهة والمنصة','مراجعة المتطلبات','توضيح خطوات التنفيذ'],color:'#e7f8f1'}
];
const contentVersion=3;
const defaults={version:contentVersion,updatedAt:null,
  settings:{brand:'مَدار',primary:'#1477c9',phone:'+966 50 000 0000',email:'hello@madar.sa',city:'الرياض، المملكة العربية السعودية',heroTitle:'كل ما تحتاجه منشأتك | في مسار واحد واضح.',heroSubtitle:'نؤسس أعمالك، ننفّذ معاملاتك، ونطوّر منظومتك الإدارية بمتابعة شفافة من أول طلب حتى الإنجاز.',motion:'on',motionLevel:'soft'},
  visibility:{visualStory:true,marquee:true,saudiValue:true,method:true,services:true,journey:true,transformation:true,solutions:true,packages:true,track:true,knowledge:true,deliverables:true,faq:true,cta:true},
  activities:[
    {id:1,tag:'الشركات والاستثمار',title:'تأسيس يراعي ما بعد إصدار السجل',desc:'نربط الكيان القانوني بالتراخيص والتشغيل وخطة النمو.',image:'assets/images/saudi-business-establishment.svg',alt:'مكتب أعمال سعودي حديث يعبّر عن تأسيس المنشأة وتشغيلها ونموها'},
    {id:2,tag:'التشغيل',title:'بيئة أكثر تنظيمًا وإجراءات أوضح',desc:'',image:'https://www.candpco.com/static/projects/UCI_1.jpg',alt:'مكتب أعمال حديث في الرياض دون أشخاص'},
    {id:3,tag:'التطوير المؤسسي',title:'استراتيجية تتحول إلى عمل قابل للقياس',desc:'',image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=82',alt:'عمارة أعمال حديثة دون أشخاص'}],
  articles:[
    {id:1,tag:'دليل التأسيس',title:'كيف تختار الكيان القانوني المناسب لمشروعك؟',desc:'مقارنة عملية تساعدك على فهم الخيارات قبل بدء الإجراءات.',image:'assets/images/company-formation.svg',alt:'مكتب تأسيس شركة سعودية مع نموذج مبنى وملف أعمال',link:'#'},
    {id:2,tag:'الحوكمة',title:'من الأهداف العامة إلى مؤشرات أداء قابلة للقياس',desc:'خطوات بناء منظومة تربط الخطة بالتنفيذ اليومي.',image:'assets/images/governance-kpi.svg',alt:'قاعة اجتماعات تنفيذية ولوحة مؤشرات للحوكمة والأداء',link:'#'},
    {id:3,tag:'دراسات الجدوى',title:'ما الذي يجعل دراسة الجدوى قابلة لاتخاذ القرار؟',desc:'العناصر المالية والسوقية والتشغيلية التي لا ينبغي تجاهلها.',image:'assets/images/feasibility-study.svg',alt:'تحليل دراسة جدوى مع مخططات مالية ومعمارية لمدينة سعودية',link:'#'}],services:defaultServices};

const publicFiles=new Set(['index.html','admin.html','app.js','admin.js','site-config.js','admin.css','madar-style-00.css','madar-style-01.css','madar-style-02.css','madar-style-03.css','assets/images/saudi-business-establishment.svg','assets/images/company-formation.svg','assets/images/governance-kpi.svg','assets/images/feasibility-study.svg','favicon.ico','robots.txt']);
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.ico':'image/x-icon'};
const securityHeaders={'content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data: https://www.hyphenksa.com https://www.candpco.com https://images.unsplash.com; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; upgrade-insecure-requests",'permissions-policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=()','strict-transport-security':'max-age=31536000; includeSubDomains','cross-origin-opener-policy':'same-origin','x-content-type-options':'nosniff','x-frame-options':'SAMEORIGIN','referrer-policy':'strict-origin-when-cross-origin'};
const sessions=new Map(),attempts=new Map();
function clean(value,max=300){return String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max)}
function json(res,status,value,extra={}){res.writeHead(status,{...securityHeaders,'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra});res.end(JSON.stringify(value))}
function send(res,status,body,extra={}){res.writeHead(status,{...securityHeaders,'content-type':'text/plain; charset=utf-8',...extra});res.end(body)}
function readContent(){try{const saved=JSON.parse(fs.readFileSync(contentFile,'utf8'));return {...defaults,...saved,version:contentVersion,services:Number(saved.version||0)<contentVersion?structuredClone(defaultServices):saved.services}}catch{return structuredClone(defaults)}}
function atomicWrite(value){const temp=contentFile+'.tmp';fs.writeFileSync(temp,JSON.stringify(value,null,2));fs.renameSync(temp,contentFile)}
function parseCookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
function isAdmin(req){const token=parseCookies(req).madar_admin,expiry=sessions.get(token);if(!expiry||expiry<Date.now()){if(token)sessions.delete(token);return false}return true}
function readJson(req,limit=3_000_000){return new Promise((resolve,reject)=>{let size=0,data='';req.on('data',chunk=>{size+=chunk.length;if(size>limit){reject(new Error('large'));req.destroy();return}data+=chunk});req.on('end',()=>{try{resolve(JSON.parse(data||'{}'))}catch{reject(new Error('json'))}});req.on('error',reject)})}
function normalizeContent(input){const current=readContent(),settings=input?.settings||{},visibility=input?.visibility||{};const safeImage=value=>{const v=clean(value,500);return /^(?:\/uploads\/[a-z0-9._-]+|assets\/images\/[a-z0-9._-]+|https:\/\/(?:www\.candpco\.com|images\.unsplash\.com)\/)/i.test(v)?v:''};const item=(x,i,type)=>({id:Number(x?.id)||Date.now()+i,tag:clean(x?.tag,40),title:clean(x?.title,120),desc:clean(x?.desc,260),image:safeImage(x?.image),alt:clean(x?.alt,160),...(type==='article'?{link:/^(?:#|https:\/\/)/.test(clean(x?.link,500))?clean(x?.link,500):'#'}:{})});const service=(x,i)=>({id:Number(x?.id)||Date.now()+i,cat:['startup','government','consulting','growth'].includes(x?.cat)?x.cat:'consulting',icon:clean(x?.icon,3)||'✦',title:clean(x?.title,80)||'خدمة أعمال',desc:clean(x?.desc,220),audience:clean(x?.audience,80),duration:clean(x?.duration,40),price:clean(x?.price,40),features:(Array.isArray(x?.features)?x.features:[]).slice(0,12).map(v=>clean(v,80)).filter(Boolean),color:/^#[0-9a-f]{6}$/i.test(x?.color)?x.color:'#e8f5fd'});return {version:contentVersion,updatedAt:new Date().toISOString(),settings:{brand:clean(settings.brand,40)||current.settings.brand,primary:/^#[0-9a-f]{6}$/i.test(settings.primary)?settings.primary:'#1477c9',phone:clean(settings.phone,24),email:clean(settings.email,100),city:clean(settings.city,100),heroTitle:clean(settings.heroTitle,140),heroSubtitle:clean(settings.heroSubtitle,300),motion:settings.motion==='off'?'off':'on',motionLevel:settings.motionLevel==='rich'?'rich':'soft'},visibility:Object.fromEntries(Object.keys(defaults.visibility).map(k=>[k,visibility[k]!==false])),activities:(Array.isArray(input?.activities)?input.activities:current.activities).slice(0,6).map((x,i)=>item(x,i,'activity')),articles:(Array.isArray(input?.articles)?input.articles:current.articles).slice(0,9).map((x,i)=>item(x,i,'article')),services:(Array.isArray(input?.services)?input.services:current.services).slice(0,100).map(service)}}

http.createServer(async(req,res)=>{let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname)}catch{return send(res,400,'طلب غير صالح')}
  if(pathname==='/health')return send(res,200,'ok',{'cache-control':'no-store'});
  if(pathname==='/api/content'&&req.method==='GET')return json(res,200,readContent());
  if(pathname==='/api/admin/session'&&req.method==='GET')return json(res,200,{authenticated:isAdmin(req),configured:Boolean(adminPassword)});
  if(pathname==='/api/admin/login'&&req.method==='POST'){const ip=req.socket.remoteAddress||'unknown',recent=(attempts.get(ip)||[]).filter(t=>Date.now()-t<900000);attempts.set(ip,recent);if(recent.length>=8)return json(res,429,{error:'محاولات كثيرة، حاول لاحقًا'});if(!adminPassword)return json(res,503,{error:'لم تُضبط كلمة مرور الإدارة بعد'});try{const body=await readJson(req,10000),supplied=Buffer.from(String(body.password||'')),expected=Buffer.from(adminPassword),valid=supplied.length===expected.length&&crypto.timingSafeEqual(supplied,expected);if(!valid){recent.push(Date.now());return json(res,401,{error:'كلمة المرور غير صحيحة'})}const token=crypto.randomBytes(32).toString('hex');sessions.set(token,Date.now()+28800000);return json(res,200,{ok:true},{'set-cookie':`madar_admin=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`})}catch{return json(res,400,{error:'طلب غير صالح'})}}
  if(pathname==='/api/admin/logout'&&req.method==='POST'){sessions.delete(parseCookies(req).madar_admin);return json(res,200,{ok:true},{'set-cookie':'madar_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'})}
  if(pathname==='/api/admin/content'&&req.method==='PUT'){if(!isAdmin(req))return json(res,401,{error:'يلزم تسجيل الدخول'});if(req.headers['x-requested-with']!=='MadarAdmin')return json(res,403,{error:'طلب غير مصرح'});try{const value=normalizeContent(await readJson(req));atomicWrite(value);return json(res,200,value)}catch(e){return json(res,e.message==='large'?413:400,{error:e.message==='large'?'حجم البيانات كبير':'تعذر حفظ البيانات'})}}
  if(pathname==='/api/admin/upload'&&req.method==='POST'){if(!isAdmin(req))return json(res,401,{error:'يلزم تسجيل الدخول'});if(req.headers['x-requested-with']!=='MadarAdmin')return json(res,403,{error:'طلب غير مصرح'});try{const body=await readJson(req,3_000_000),match=String(body.data||'').match(/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/);if(!match)return json(res,415,{error:'استخدم JPG أو PNG أو WebP فقط'});const buffer=Buffer.from(match[2],'base64');if(buffer.length>2_000_000)return json(res,413,{error:'الحد الأقصى للصورة 2 ميجابايت'});const ext=match[1]==='jpeg'?'jpg':match[1],name=`${Date.now()}-${crypto.randomBytes(6).toString('hex')}.${ext}`;fs.writeFileSync(path.join(uploadsDir,name),buffer,{flag:'wx'});return json(res,201,{url:`/uploads/${name}`})}catch{return json(res,400,{error:'تعذر رفع الصورة'})}}
  if(!['GET','HEAD'].includes(req.method))return send(res,405,'الطريقة غير مسموحة',{'allow':'GET, HEAD'});
  const requested=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),isUpload=requested.startsWith('uploads/');let filePath;if(isUpload){const name=path.basename(requested);if(name!==requested.slice(8))return send(res,404,'الصفحة غير موجودة');filePath=path.join(uploadsDir,name)}else{if(!publicFiles.has(requested))return send(res,404,'الصفحة غير موجودة');filePath=path.join(root,requested)}const relative=path.relative(isUpload?uploadsDir:root,filePath);if(relative.startsWith('..')||path.isAbsolute(relative)||!fs.existsSync(filePath)||fs.statSync(filePath).isDirectory())return send(res,404,'الصفحة غير موجودة');const extension=path.extname(filePath).toLowerCase();res.writeHead(200,{...securityHeaders,'content-type':mime[extension]||'application/octet-stream','cache-control':extension==='.html'?'no-cache, no-store, must-revalidate':'public, max-age=86400'});if(req.method==='HEAD')return res.end();fs.createReadStream(filePath).on('error',()=>res.destroy()).pipe(res)
}).listen(port,'0.0.0.0',()=>console.log(`Madar is running on port ${port}`));
